spring:
  datasource:
    url: jdbc:mysql://localhost/thymeleaf?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: sboot
    password: sboot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
